version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_server
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
